name: First Work Flows

on:   
    push:
      branches:
         - main
                 

jobs:
  example-job:
     runs-on: ubuntu-latest

     steps:
      - name: "Welcome message"
        run: echo "First git workflow action" 
         
